name: Master
on:
  push:
    branches:
      - 'master'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.29

  releases-matrix:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: amd64
