name: Master
on:
  push:
    branches:
      - 'master'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: v1.29

  releases-matrix:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
    steps:
      - uses: actions/checkout@v2
      - uses: ngs/go-release.action@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BINARY_NAME: dotfiles
          GOOS: ${{ matrix.goos }}
          GOARCH: amd64

